name = "lamarck-landing"
main = "src/worker.ts"
compatibility_date = "2026-06-25"
workers_dev = true
preview_urls = true

[[routes]]
pattern = "lamarck.ai"
custom_domain = true

[[routes]]
pattern = "www.lamarck.ai"
custom_domain = true

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
